### ISSUE TITLE
error: flag provided but not defined: --preseed

### ISSUE THREAD

**Issue by anicet1** [bobjolliffe/dhis2-tools-ng#1]
After running ./lxd_setup.sh I get this error:
error: flag provided but not defined: --preseed
And the installation stops.
I use Xubuntu 16.04, with lxd v2.0.0

**Comment by bobjolliffe** [comment]
These tools are only tested on ubuntu 18.04.  We will probably also soon port to 20.04.  There is no plan to support 16.04 :-(
